package io.quarkiverse.quinoa.deployment.sbom;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;

import jakarta.json.Json;
import jakarta.json.JsonArray;
import jakarta.json.JsonObject;
import jakarta.json.JsonReader;
import jakarta.json.JsonString;
import jakarta.json.JsonValue;

import io.quarkus.sbom.ComponentDependencies;
import io.quarkus.sbom.ComponentDescriptor;
import io.quarkus.sbom.Purl;
import io.quarkus.sbom.SbomContribution;

/**
 * Parses CycloneDX JSON output into an {@link SbomContribution}.
 */
public final class CycloneDxBomParser {

    private static final String DEV_PROPERTY = "cdx:npm:package:development";

    private CycloneDxBomParser() {
    }

    /**
     * Parses a CycloneDX JSON file and a {@code package.json} to produce an SBOM contribution.
     *
     * @param cycloneDxJson path to the CycloneDX JSON file generated by cdxgen
     * @param packageJson path to the project's {@code package.json} for top-level detection
     * @return an SBOM contribution with components and dependency relationships
     * @throws IOException if the files cannot be read
     */
    public static SbomContribution parse(Path cycloneDxJson, Path packageJson) throws IOException {
        final Set<String> directDeps = collectDirectDependencyNames(packageJson);

        final JsonObject bom;
        try (InputStream in = Files.newInputStream(cycloneDxJson);
                JsonReader reader = Json.createReader(in)) {
            bom = reader.readObject();
        }

        final JsonArray components = bom.getJsonArray("components");
        if (components == null || components.isEmpty()) {
            return SbomContribution.ofComponents(List.of());
        }

        final LinkedHashMap<String, ComponentDescriptor> byBomRef = new LinkedHashMap<>();
        for (JsonValue cv : components) {
            final JsonObject comp = cv.asJsonObject();
            final ComponentDescriptor descriptor = parseComponent(comp, directDeps);
            if (descriptor != null) {
                byBomRef.put(descriptor.getBomRef(), descriptor);
            }
        }

        final List<ComponentDependencies> dependencies = parseDependencies(bom, byBomRef.keySet());

        return SbomContribution.of(List.copyOf(byBomRef.values()), dependencies);
    }

    /**
     * Returns a new contribution with development-scoped components removed.
     *
     * @param contribution the original contribution
     * @return a filtered contribution, or the original if no dev components are present
     */
    public static SbomContribution excludeDevDependencies(SbomContribution contribution) {
        final Set<String> retainedRefs = new HashSet<>();
        final List<ComponentDescriptor> filtered = new ArrayList<>();
        for (ComponentDescriptor c : contribution.components()) {
            if (!ComponentDescriptor.SCOPE_DEVELOPMENT.equals(c.getScope())) {
                filtered.add(c);
                retainedRefs.add(c.getBomRef());
            }
        }
        if (filtered.size() == contribution.components().size()) {
            return contribution;
        }
        if (filtered.isEmpty()) {
            return SbomContribution.ofComponents(List.of());
        }
        final List<ComponentDependencies> filteredDeps = new ArrayList<>();
        for (ComponentDependencies dep : contribution.dependencies()) {
            if (!retainedRefs.contains(dep.getBomRef())) {
                continue;
            }
            final List<String> retainedDependsOn = new ArrayList<>();
            for (String ref : dep.getDependsOn()) {
                if (retainedRefs.contains(ref)) {
                    retainedDependsOn.add(ref);
                }
            }
            if (!retainedDependsOn.isEmpty()) {
                filteredDeps.add(ComponentDependencies.of(dep.getBomRef(), retainedDependsOn));
            }
        }
        return SbomContribution.of(filtered, filteredDeps);
    }

    private static ComponentDescriptor parseComponent(JsonObject comp, Set<String> directDeps) {
        final String purlStr = getStringOrNull(comp, "purl");
        if (purlStr == null) {
            return null;
        }

        final Purl purl = Purl.parse(purlStr);

        final String bomRef = getStringOrNull(comp, "bom-ref");
        final String integrity = extractIntegrity(comp);
        final boolean isDev = isDevDependency(comp);
        final String scope = isDev ? ComponentDescriptor.SCOPE_DEVELOPMENT : ComponentDescriptor.SCOPE_RUNTIME;

        final String fullName = purl.getNamespace() != null
                ? purl.getNamespace() + "/" + purl.getName()
                : purl.getName();
        final boolean topLevel = directDeps.contains(fullName);

        final ComponentDescriptor.Builder builder = ComponentDescriptor.builder()
                .setPurl(purl)
                .setBomRef(bomRef != null ? bomRef : purlStr)
                .setIntegrity(integrity)
                .setScope(scope)
                .setTopLevel(topLevel);
        return builder.build();
    }

    private static String extractIntegrity(JsonObject comp) {
        final JsonArray hashes = comp.getJsonArray("hashes");
        if (hashes == null || hashes.isEmpty()) {
            return null;
        }
        String bestAlg = null;
        String bestContent = null;
        int bestRank = -1;
        for (JsonValue hv : hashes) {
            final JsonObject hash = hv.asJsonObject();
            final String alg = getStringOrNull(hash, "alg");
            final String content = getStringOrNull(hash, "content");
            if (alg == null || content == null) {
                continue;
            }
            final int rank = hashRank(alg);
            if (rank > bestRank) {
                bestRank = rank;
                bestAlg = alg;
                bestContent = content;
                if (rank == 4) {
                    break;
                }
            }
        }
        if (bestAlg == null) {
            return null;
        }
        return toSriIntegrity(bestAlg, bestContent);
    }

    /**
     * Converts a CycloneDX hash into SRI format ({@code algorithm-base64digest}).
     * CycloneDX spec requires hex-encoded content, but some tools pass through
     * base64 from npm. This method handles both encodings.
     */
    static String toSriIntegrity(String alg, String content) {
        final String prefix = alg.toLowerCase().replace("-", "");
        if (isHexEncoded(content)) {
            final byte[] bytes = hexToBytes(content);
            return prefix + "-" + Base64.getEncoder().encodeToString(bytes);
        }
        return prefix + "-" + content;
    }

    private static boolean isHexEncoded(String s) {
        if (s.isEmpty() || s.length() % 2 != 0) {
            return false;
        }
        for (int i = 0; i < s.length(); i++) {
            final char c = s.charAt(i);
            if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'))) {
                return false;
            }
        }
        return true;
    }

    private static byte[] hexToBytes(String hex) {
        final byte[] bytes = new byte[hex.length() / 2];
        for (int i = 0; i < bytes.length; i++) {
            bytes[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
        }
        return bytes;
    }

    private static int hashRank(String alg) {
        return switch (alg) {
            case "SHA-512" -> 4;
            case "SHA-384" -> 3;
            case "SHA-256" -> 2;
            case "SHA-1" -> 1;
            default -> 0;
        };
    }

    private static boolean isDevDependency(JsonObject comp) {
        final JsonArray properties = comp.getJsonArray("properties");
        if (properties != null) {
            for (JsonValue pv : properties) {
                final JsonObject prop = pv.asJsonObject();
                if (DEV_PROPERTY.equals(getStringOrNull(prop, "name"))) {
                    return "true".equals(getStringOrNull(prop, "value"));
                }
            }
        }
        return false;
    }

    private static List<ComponentDependencies> parseDependencies(JsonObject bom, Set<String> knownBomRefs) {
        final JsonArray deps = bom.getJsonArray("dependencies");
        if (deps == null || deps.isEmpty()) {
            return List.of();
        }

        final List<ComponentDependencies> result = new ArrayList<>();
        for (JsonValue dv : deps) {
            final JsonObject dep = dv.asJsonObject();
            final String ref = getStringOrNull(dep, "ref");
            if (ref == null || !knownBomRefs.contains(ref)) {
                continue;
            }
            final JsonArray dependsOn = dep.getJsonArray("dependsOn");
            if (dependsOn == null || dependsOn.isEmpty()) {
                continue;
            }
            final List<String> resolved = new ArrayList<>();
            for (JsonValue rv : dependsOn) {
                if (rv.getValueType() != JsonValue.ValueType.STRING) {
                    continue;
                }
                final String depRef = ((JsonString) rv).getString();
                if (knownBomRefs.contains(depRef)) {
                    resolved.add(depRef);
                }
            }
            if (!resolved.isEmpty()) {
                result.add(ComponentDependencies.of(ref, resolved));
            }
        }
        return result;
    }

    private static Set<String> collectDirectDependencyNames(Path packageJson) throws IOException {
        if (packageJson == null || !Files.isRegularFile(packageJson)) {
            return Set.of();
        }
        final JsonObject pkg;
        try (InputStream in = Files.newInputStream(packageJson);
                JsonReader reader = Json.createReader(in)) {
            pkg = reader.readObject();
        }
        final Set<String> names = new HashSet<>();
        addKeys(pkg, "dependencies", names);
        addKeys(pkg, "devDependencies", names);
        addKeys(pkg, "optionalDependencies", names);
        return names;
    }

    private static void addKeys(JsonObject obj, String field, Set<String> target) {
        final JsonObject sub = obj.getJsonObject(field);
        if (sub != null) {
            target.addAll(sub.keySet());
        }
    }

    private static String getStringOrNull(JsonObject obj, String key) {
        final JsonValue value = obj.get(key);
        if (value != null && value.getValueType() == JsonValue.ValueType.STRING) {
            return ((JsonString) value).getString();
        }
        return null;
    }
}
