= Quarkus - Quinoa
:extension-status: experimental

include::./includes/attributes.adoc[]

Quinoa is a Quarkus extension which eases the development, the build and serving single page apps or web components (built with NodeJS: React, Angular, Vue, Lit, …) alongside other Quarkus services (REST, GraphQL, Security, Events, ...).

Live code the backend and frontend together with close to no configuration. When enabled in development mode, Quinoa will start the UI live coding server provided by the target framework and forward relevant requests to it. In production mode, Quinoa will run the build and process the generated files to serve them at runtime.

== How it works

=== The Quinoa build (using npm)

[mermaid]
....
flowchart LR
    q-build[quarkus build] -->|Other extensions| target(Jar or Binary )
    q-build --> quinoa[Quinoa]
    quinoa -->|npm run build| generated-web-resources(Generated web resources: html, js, css, images)
    generated-web-resources -->|copy as generated Web Resources| target
....

NOTE: packages are installed by Quinoa before the build when needed (i.e `npm install`). See link:#install-packages[Packages installation]. Quinoa is pre-configured to work with your favorite link:#package-manager[package manager] (npm, yarn or pnpm).

=== Runtime for production mode

[mermaid]
....
flowchart LR
    run[run - jar or binary] --> vertx(Vert.x routes)
    vertx -->|GET /something| quinoa{is this a Quinoa Web Resources?}
    quinoa -->|yes| handle[Serve]
    quinoa -->|no| static-resources{is this a META-INF/resources?}
    static-resources -->|yes| handle[Serve]
    static-resources -->|no| rest{is this a REST resource?}
    rest -->|yes| handle[Handle]
    rest -->|no| 404[404]
....

=== Runtime for full Quarkus live-coding

Quinoa (using Quarkus live-coding watch feature) will watch the Web UI directory and trigger a new build on changes. It works the same as the production mode. This option is perfect for small/fast builds.

NOTE: You can differentiate the build for link:#build-mode[dev mode]. e.g to disable minification.

=== Runtime for proxied live-coding (e.g on port 3000)

[mermaid]
....
flowchart LR
    dev[quarkus dev] --> vertx(Vert.x routes)
    vertx -->|GET /something| quinoa{try /something on port 3000?}
    quinoa -->|200| forward[Forward Response]
    quinoa -->|error| forward-error[Forward Error]
    quinoa -->|404| static-resources{is this a META-INF/resources?}
    static-resources -->|yes| handle[Serve]
    static-resources -->|no| rest{is this a REST resource?}
    rest -->|yes| handle[Handle]
    rest -->|no| 404[404]
....

NOTE: Quarkus live-coding will keep watching for the backend changes as usual.

See link:#dev-server[Enable the proxied live coding].

== Prerequisite

* Install NodeJS (https://nodejs.org/)
* Create or use an existing Quarkus application
* Add the Quinoa extension

[#installation]
== Installation

To use this, you need the `io.quarkiverse.quinoa:quarkus-quinoa` extension first.

Create a new Quinoa project (with a base Quinoa starter code):

* With https://code.quarkus.io/?a=quinoa-bowl&j=17&e=io.quarkiverse.quinoa%3Aquarkus-quinoa[code.quarkus.io]
* With the https://quarkus.io/guides/cli-tooling[Quarkus CLI]:
[source,bash]
----
quarkus create app quinoa-app -x=io.quarkiverse.quinoa:quarkus-quinoa
----

Then start the live-coding:
[source,bash]
----
quarkus dev
----

And navigate to http://0.0.0.0:8080/quinoa.html

You could also just add the extension (but you won't get the starter code):

* With the https://quarkus.io/guides/cli-tooling[Quarkus CLI]:
[source,bash]
----
quarkus ext add io.quarkiverse.quinoa:quarkus-quinoa
----
* In your `pom.xml` file, add this dependency:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.quinoa</groupId>
    <artifactId>quarkus-quinoa</artifactId>
    <version>{quarkus-quinoa-version}</version>
</dependency>
----

[#getting-started]
== Getting Started

Create a Web UI directory in `src/main/webui`. This directory will contain your NodeJS Web application code with a `package.json`. The location is configurable, the directory could be outside the Quarkus project as soon as the file are available at build time.
[source,properties]
----
quarkus.quinoa.ui-dir=../my-webui
----

From here, copy your existing Web UI or generate an application from any existing Node based Web UI framework such as <<react>>, <<angular>>, Lit, Webpack, Rollup, ... or your own. Example:


The key points are the `package.json` scripts (`build` and optionally `test`) and the directory where the web files (index.html, scripts, ...) are generated (by default, it will use `build/` relative to the `ui-dir`).

Quinoa provides two options for live-coding:

* Delegate to the <<dev-server>>. To enable it, configure the port of the UI server. By convention Quinoa will call the `start` script from the `package.json` to start the UI server process. Then it will transparently proxy relevant requests to the given port.
* Quarkus watches the files and Quinoa triggers a new Web UI build on changes (you can configure different builds for dev and prod).

Start the Quarkus live coding:
[source,shell]
----
$ quarkus dev
----

*It's done!* The web application is now built alongside Quarkus, dev-mode is available, and the generated files will be automatically copied to the right place and be served by Quinoa if you hit http://localhost:8080

[source,shell]
----
2022-03-28 09:24:46,739 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa target directory: 'xxx/target/quinoa-build'
2022-03-28 09:24:46,739 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa generated resource: '/favicon.ico'
2022-03-28 09:24:46,740 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa generated resource: '/index.html'
2022-03-28 09:24:46,741 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa generated resource: '/simple-greeting.js'
----

WARNING: With Quinoa, you don't need to manually copy the files to `META-INF/resources`. Quinoa has its own system and will provide another Vert.x route for it. *If you have conflicting files with `META-INF/resources`, Quinoa will have priority over them.*

[#how-to]
== How to use the extension.

=== Configure the build
Add a `build` script in the `package.json` to generate your web application index.html, scripts and media (styles, images, ...) in the `./build` directory (can be changed in the config):
[source,json]
----
 "scripts": {
    "start": "[start the Web UI live coding server]",
    "build": "[build the Web UI]",
    "test": "[test the Web UI]"
  },
----

[#build-mode]
You can differentiate dev from production builds using the `MODE` environment variable (`dev`, `prod`, `test`):
[source,json]
----
 "scripts": {
        "build": "if [[ $MODE == \"dev\" ]]; then webpack --mode=development; else webpack --mode=production; fi",
  },
----

[#package-manager]
=== Package manager

It is not necessary (but possible) to configure the package manager (NPM, Yarn or PNPM), it will be auto-detected depending on the project lockfile, NPM is the fallback:

* Use `quarkus.quinoa.package-manager` if present
* Else if `yarn.lock` then *Yarn*
* Else if `pnpm-lock.yaml` then *PNPM*
* Else *NPM*

NOTE: Quinoa is configured with the commands to call depending on the chosen package manager (to always keep the same behavior and make it easy to switch).

[#install-packages]
=== Node packages installation (node_modules)

By default, Quinoa will call the appropriate package manager install command (before building or starting) *only if* the `node_modules` directory doesn't exist.

You may force a new installation using `-Dquarkus.quinoa.always-install=true`.

[#frozen-lockfile]
NOTE: Quinoa will use the appropriate package manager frozen-lockfile command when installing, if the environment `CI=true`, or if `quarkus.quinoa.frozen-lockfile=true`. In this mode, the lockfile have to be present in the project.

[#dev-server]
=== UI live-coding dev server (proxy mode)

To enable the UI live-coding dev server, set a `start` script and set the port in the app config. Quinoa will transparently proxy relevant requests to the given port:
[source,properties]
----
quarkus.quinoa.dev-server-port=3000
----

[#react]
=== React

App created by Create React App (https://create-react-app.dev/docs/getting-started) are compatible without any change.

To enable React live coding server:
[source,properties]
----
quarkus.quinoa.dev-server-port=3000
----

[#angular]
=== Angular

App created by `ng` (https://angular.io/guide/setup-local) require a tiny bit of configuration:
[source,properties]
----
quarkus.quinoa.build-dir=dist/[your-app-name]
----

To enable Angular live coding server, you need to edit the package.json start script with `ng serve --host 0.0.0.0 --no-live-reload`, then add this configuration:
[source,properties]
----
quarkus.quinoa.dev-server-port=4200
----

If you want to use the Angular tests (instead of Playwright from the @QuarkusTest):

Change the package.json test script:
[source,json]
----
  "scripts": {
    ...
    "test": "ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI"
  },
----

Edit the karma.conf.js:
[source,javascript]
----
  browsers: ['Chrome', 'ChromeHeadless', 'ChromeHeadlessCI'],
  customLaunchers: {
    ChromeHeadlessCI: {
      base: 'ChromeHeadless',
      flags: ['--no-sandbox']
    }
},
----

[#spa-routing]
=== Single Page application routing

Client-side/Browser/SPA routing is the internal handling of a route from the javascript in the browser. It uses the https://developer.mozilla.org/en-US/docs/Web/API/History[HTML5 History API]

When enabled, to allow SPA routing, all relevant requests will be internally re-routed to index.html, this way the javascript can take care of the route inside the web-application.

To enable Single Page application routing:
[source,properties]
----
quarkus.quinoa.enable-spa-routing=true
----

NOTE: By default, Quinoa will ignore `quarkus.rest.path`, `quarkus.resteasy.path` and `quarkus.http.non-application-root-path` path prefixes. You can specify different path prefixes to ignore using `quarkus.quinoa.ignored-path-prefixes`.

WARNING: Currently, for technical reasons, the Quinoa SPA routing configuration won't work with RESTEasy Classic. Instead, you may use a workaround (if your app has all the rest resources under the same path prefix):
[source,java]
----
@ApplicationScoped
public class SPARouting {
    private static final String[] PATH_PREFIXES = { "/api/", "/q/" };
    private static final Predicate<String> FILE_NAME_PREDICATE = Pattern.compile(".*[.][a-zA-Z\\d]+").asMatchPredicate();

    public void init(@Observes Router router) {
        router.get("/*").handler(rc -> {
            final String path = rc.normalizedPath();
            if (!path.equals("/")
                    && Stream.of(PATH_PREFIXES).noneMatch(path::startsWith)
                    && !FILE_NAME_PREDICATE.test(path)) {
                rc.reroute("/");
            } else {
                rc.next();
            }
        });
    }
}
----

[#headers]
=== Http Headers

It's very common to set up headers for caching on static resources, for example React proposes https://create-react-app.dev/docs/production-build/#static-file-caching[this configuration]:

To configure Quarkus with those headers :
[source,properties]
----
quarkus.http.filter.others.header.Cache-Control=no-cache
quarkus.http.filter.others.matches=/.*
quarkus.http.filter.others.methods=GET
quarkus.http.filter.others.order=0
quarkus.http.filter.static.header.Cache-Control=max-age=31536000
quarkus.http.filter.static.matches=/static/.+
quarkus.http.filter.static.methods=GET
quarkus.http.filter.static.order=1
----

=== Testing

By default, the Web UI is not build/served in `@QuarkusTest`. The goal is to be able to test your api without having to wait for the Web UI build.

Quinoa features a testing library to make it easier to test your Web UI:
[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.quinoa</groupId>
    <artifactId>quarkus-quinoa-testing</artifactId>
    <version>{quarkus-quinoa-version}</version>
    <scope>test</scope>
</dependency>
----

In order to enable the Web UI (build and serve) in a particular test, you can use the `Enable` test profile:

[source,java]
----
@QuarkusTest
@TestProfile(QuinoaTestProfiles.Enable.class)
public class MyWebUITest {
    @Test
    public void someTest() {
    }
}
----

If you also want to run the tests included in your Web UI (i.e npm test) alongside this class, you can use the `EnableAndRunTests` test profile:

The library also brings a very elegant way to do e2e testing using https://github.com/microsoft/playwright-java[Playright]:
[source,java]
----
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Response;
import io.quarkiverse.quinoa.testing.QuarkusPlaywrightManager;
import io.quarkiverse.quinoa.testing.QuinoaTestProfiles;
import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.common.http.TestHTTPResource;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.junit.TestProfile;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.net.URL;

@QuarkusTest
@TestProfile(QuinoaTestProfiles.Enable.class)
@QuarkusTestResource(QuarkusPlaywrightManager.class)
public class MyWebUITest {
    @QuarkusPlaywrightManager.InjectPlaywright
    BrowserContext context;

    @TestHTTPResource("/")
    URL url;

    @Test
    void name() {
        final Page page = context.newPage();
        Response response = page.navigate(url.toString());
        Assertions.assertEquals("OK", response.statusText());

        page.waitForLoadState();

        String title = page.title();
        Assertions.assertEquals("My App", title);

        // Make sure the app content is ok
        String greeting = page.innerText(".quinoa");
        Assertions.assertEquals("Hello World", greeting);
    }
}
----

=== CI

Most CI images already include NodeJS. if they don't, just make sure to install it alongside Maven/Gradle (and Yarn/PNPM if needed). Then you can use it like any Maven/Gradle project.

Quinoa can be configured to install packages with a link:#frozen-lockfile[frozen lockfile].

On compatible CIs, don't forget to enable the Maven/Gradle and NPM/Yarn repository caching.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-quinoa.adoc[leveloffset=+1, opts=optional]
