= Quarkus - Quinoa
:extension-status: experimental

Quinoa is a Quarkus extension which eases the development, the build and serving single page apps or web components (built with NodeJS: React, Angular, Vue, Lit, …) alongside other Quarkus services (REST, GraphQL, Security, Events, ...).

Live code the backend and frontend together with close to no configuration. When enabled in development mode, Quinoa will start the UI live coding server provided by the target framework and forward relevant requests to it. In production mode, Quinoa will run the build and process the generated files to serve them at runtime.

== Prerequisite

* Install NodeJS (https://nodejs.org/)
* Create or use an existing Quarkus application
* Add the Quinoa extension

[#installation]
== Installation

To use this, you need the `io.quarkiverse.quinoa:quarkus-quinoa` extension first.

Create a new Quinoa project (with a base Quinoa starter code):

* With https://code.quarkus.io/?a=quinoa-bowl&j=17&e=io.quarkiverse.quinoa%3Aquarkus-quinoa[code.quarkus.io]
* With the https://quarkus.io/guides/cli-tooling[Quarkus CLI]:
[source,bash]
----
quarkus create app quinoa-app -x=io.quarkiverse.quinoa:quarkus-quinoa
----

Then start the live-coding:
[source,bash]
----
quarkus dev
----

And navigate to http://0.0.0.0:8080/quinoa.html

You could also just add the extension (but you won't get the starter code):

* With the https://quarkus.io/guides/cli-tooling[Quarkus CLI]:
[source,bash]
----
quarkus ext add io.quarkiverse.quinoa:quarkus-quinoa
----
* In your `pom.xml` file, add (with a valid version):

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.quinoa</groupId>
    <artifactId>quarkus-quinoa</artifactId>
    <version>...</version>
</dependency>
----

You may find the latest release version here:
image:https://img.shields.io/maven-central/v/io.quarkiverse.quinoa/quarkus-quinoa.svg?label=Maven%20Central[link=https://search.maven.org/artifact/io.quarkiverse.quinoa/quarkus-quinoa]

[#getting-started]
== Getting Started

Create a Web UI directory in `src/main/webui`. This directory will contain your NodeJS Web application code with a `package.json`. The location is configurable, the directory could be outside the Quarkus project as soon as the file are available at build time.
[source,properties]
----
quarkus.quinoa.ui-dir=../my-webui
----

From here, copy your existing Web UI or generate an application from any existing Node based Web UI framework such as <<react>>, <<angular>>, Lit, Webpack, Rollup, ... or your own. Example:


The key points are the `package.json` scripts (`build` and optionally `test`) and the directory where the web files (index.html, scripts, ...) are generated (by default, it will use `build/` relative to the `ui-dir`).

Quinoa provides two options for live-coding:

* Delegate to the <<dev-server>>. To enable it, configure the port of the UI server. By convention Quinoa will call the `start` script from the `package.json` to start the UI server process. Then it will transparently proxy relevant requests to the given port.
* Quarkus watches the files and Quinoa triggers a new Web UI build on changes (you can configure different builds for dev and prod).

Start the Quarkus live coding:
[source,shell]
----
$ mvn quarkus:dev
----

*It's done!* The web application is now built alongside Quarkus, dev-mode is available, and the generated files will be automatically copied to the right place and be served by Quinoa if you hit http://localhost:8080

[source,shell]
----
2022-03-28 09:24:46,739 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa target directory: 'xxx/target/quinoa-build'
2022-03-28 09:24:46,739 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa generated resource: '/favicon.ico'
2022-03-28 09:24:46,740 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa generated resource: '/index.html'
2022-03-28 09:24:46,741 INFO  [io.qua.qui.dep.QuinoaProcessor] (build-25) Quinoa generated resource: '/simple-greeting.js'
----

NOTE: With Quinoa, you don't need to manually copy the files to `META-INF/resources`. Quinoa has its own system and will provide another Vert.x route for it. If you have conflicting files in `META-INF/resources`, they will have priority over Quinoa.

[#how-to]
== How to use the extension.

=== Configure the build
Add a `build` script in the `package.json` to generate your web application index.html, scripts and media (styles, images, ...) in the `./build` directory (can be changed in the config):
[source,json]
----
 "scripts": {
    "start": "[start the Web UI live coding server]",
    "build": "[build the Web UI]",
    "test": "[test the Web UI]"
  },
----

You can differentiate dev from production builds using the `MODE` environment variable (`dev`, `prod`, `test`):
[source,json]
----
 "scripts": {
        "build": "if [[ $MODE == \"dev\" ]]; then webpack --mode=development; else webpack --mode=production; fi",
  },
----

[#dev-server]
=== UI live-coding dev server

To enable the UI live-coding dev server, set a `start` script and set the port in the app config. Quinoa will transparently proxy relevant requests to the given port:
[source,properties]
----
quarkus.quinoa.dev-server-port=3000
----

[#react]
=== React

App created by Create React App (https://create-react-app.dev/docs/getting-started) are compatible without any change.

To enable React live coding server:
[source,properties]
----
quarkus.quinoa.dev-server-port=3000
----

[#angular]
=== Angular

App created by `ng` (https://angular.io/guide/setup-local) require a tiny bit of configuration:
[source,properties]
----
quarkus.quinoa.build-dir=dist/[your-app-name]
----

To enable Angular live coding server, you need to edit the package.json start script with `ng serve --host 0.0.0.0 --no-live-reload`, then add this configuration:
[source,properties]
----
quarkus.quinoa.dev-server-port=4200
----

If you want to use the Angular tests (instead of Playwright from the @QuarkusTest):

Change the package.json test script:
[source,json]
----
  "scripts": {
    ...
    "test": "ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI"
  },
----

Edit the karma.conf.js:
[source,javascript]
----
  browsers: ['Chrome', 'ChromeHeadless', 'ChromeHeadlessCI'],
  customLaunchers: {
    ChromeHeadlessCI: {
      base: 'ChromeHeadless',
      flags: ['--no-sandbox']
    }
},
----

[#spa-routing]
=== Single Page application routing

Client-side/Browser/SPA routing is the internal handling of a route from the javascript in the browser. It uses the https://developer.mozilla.org/en-US/docs/Web/API/History[HTML5 History API]

When enabled, to allow SPA routing, all unhandled requests will be internally re-routed to index.html, this way the javascript can take care of the route inside the web-application.

To enable Single Page application routing:
[source,properties]
----
quarkus.quinoa.enable-spa-routing=true
----

[#headers]
=== Http Headers

It's very common to set up headers for caching on static resources, for example React proposes https://create-react-app.dev/docs/production-build/#static-file-caching[this configuration]:

To configure Quarkus with those headers :
[source,properties]
----
quarkus.http.filter.others.header.Cache-Control=no-cache
quarkus.http.filter.others.matches=/.*
quarkus.http.filter.others.methods=GET
quarkus.http.filter.others.order=0
quarkus.http.filter.static.header.Cache-Control=max-age=31536000
quarkus.http.filter.static.matches=/static/.+
quarkus.http.filter.static.methods=GET
quarkus.http.filter.static.order=1
----

=== Testing

By default, the Web UI is not build/served in `@QuarkusTest`. The goal is to be able to test your api without having to wait for the Web UI build.

Quinoa features a testing library to make it easier to test your Web UI:
[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.quinoa</groupId>
    <artifactId>quarkus-quinoa-testing</artifactId>
    <scope>test</scope>
</dependency>
----

In order to enable the Web UI (build and serve) in a particular test, you can use the `Enable` test profile:

[source,java]
----
    @QuarkusTest
    @TestProfile(QuinoaTestProfiles.Enable.class)
    public class MyWebUITest {
        @Test
        public void someTest() {
        }
    }
----

If you also want to run the tests included in your Web UI (i.e npm test) alongside this class, you can use the `EnableAndRunTests` test profile:

The library also brings a very elegant way to do e2e testing using https://github.com/microsoft/playwright-java[Playright]:
[source,java]
----
    @QuarkusTest
    @TestProfile(QuinoaTestProfiles.Enable.class)
    @QuarkusTestResource(QuarkusPlaywrightManager.class)
    public class MyWebUITest {
        @PlaywrightManager.InjectPlaywright
        BrowserContext context;

        @TestHTTPResource("/")
        URL url;

        @Test
        void name() {
            final Page page = context.newPage();
            Response response = page.navigate(url.toString());
            Assertions.assertEquals("OK", response.statusText());

            page.waitForLoadState();

            String title = page.title();
            Assertions.assertEquals("My App", title);

            // Make sure the app content is ok
            String greeting = page.innerText(".quinoa");
            Assertions.assertEquals("Hello World", greeting);
        }
    }
----

=== CI

Most CI images already include NodeJS. if they don't, just make sure to install it alongside Maven/Gradle (and Yarn/PNPM if needed). Then you can use it like any Maven/Gradle project.

On compatible CIs, don't forget to enable the Maven and NPM/Yarn repository caching.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-quinoa.adoc[leveloffset=+1, opts=optional]
