= Quarkus Quinoa - Web Frameworks

include::./includes/attributes.adoc[]

Quinoa attempts to automatically determine which framework you are using by reading your package.json file and auto-configure settings for that framework. When possible, if some changes are required in the Web UI, it will try to help you configure it.

For developers, this provides more "convention over configuration" approach for a smoother experience.

== Detected Frameworks

[cols="^.^2,^.^1,3,1,1"]
|===
|Name|Preconfigured|Starter|Guides|Config

a|
[#react]
=== React
|✓
a|
[source,bash]
----
npx create-react-app my-app
----
a|
- https://create-react-app.dev/docs/getting-started[Create React App]
- https://github.com/timarney/react-app-rewired[React App Rewired]
- https://craco.js.org/[CRACO]
|

a|
[#vue]
=== Vue
|✓
a|
[source,bash]
----
npm create vue@latest
----
a|
- https://cli.vuejs.org/guide/cli-service.html[Vue CLI Service]
- https://github.com/vuejs/create-vue[Create Vue]
|

a|
[#angular]
=== Angular
|✓*
a|
[source,bash]
----
npm install -g @angular/cli
ng new my-first-project
----
a|
- https://angular.io/guide/setup-local[ng]
| <<angular-test-config>>

a|
[#nextjs]
=== Next.js
|~
a|
[source,bash]
----
npx create-next-app@latest
----
a|
- https://nextjs.org/docs[Next]
| <<nextjs-config>>

a|
[#vite]
=== Vite
|✓
a|
[source,bash]
----
npm create vite@latest
----
a|
- https://vitejs.dev/guide/[Vite]
| <<vite-config>>

a|
[#svelte-kit]
=== Svelte Kit
|~
a|
[source,bash]
----
npm create svelte@latest webui
----
a|
- https://kit.svelte.dev/[Svelte Kit]
| <<svelte-kit-config>>

a|
[#nuxt]
=== Nuxt
|✓
a|
[source,bash]
----
npm init nuxt-app <project-name>
----
a|
- https://v2.nuxt.com/docs/get-started/installation#set-up-your-project[Nuxt]
|

a|
[#solidstart]
=== Solid Start
|✓
a|
[source,bash]
----
mkdir my-app && cd my-app
npm init solid@latest
----
a|
- https://start.solidjs.com/getting-started/what-is-solidstart[SolidStart]
|

a|
[#astro]
=== Astro
|✓
a|
[source,bash]
----
npm create astro@latest
----
a|
- https://astro.build/[Astro]
|

a|
[#gatsby]
=== Gatsby
|✓
a|
[source,bash]
----
npm init gatsby@latest
----
a|
- https://www.gatsbyjs.com/docs/quick-start/[Gatsby]
|

a|
[#ember]
=== Ember
|✓
a|
[source,bash]
----
npm install -g ember-cli
ember new ember-quickstart
----
a|
- https://guides.emberjs.com/release/getting-started/[Ember]
|



a|
[#midwayjs]
=== Midway.js
|✓
| No
a|
- https://www.midwayjs.org/[Midway.js]
|

|===

== Required Configuration

[#angular-test-config]
=== Angular Test Configuration

If you want to use the Angular tests (instead of Playwright from the @QuarkusTest):

.karma.conf.js:
[source,javascript]
----
  browsers: ['Chrome', 'ChromeHeadless', 'ChromeHeadlessCI'],
  customLaunchers: {
    ChromeHeadlessCI: {
      base: 'ChromeHeadless',
      flags: ['--no-sandbox']
    }
},
----

[#nextjs-config]
=== Next.js Configuration

This will configure the build to export the static files:
.package.json:
[source,json]
----
  "scripts": {
    ...
    "build": "next build",
  }
----

In Next.js 14+ you need to add the following property in `next.config.js` file:
----
const nextConfig = {
  output: 'export',  
}
----

[#vite-config]
=== Vite Configuration
Configure `vite.config.ts` file with the following changes:
[source,javascript]
----
  export default defineConfig({
    // depending on your application, base can also be "/"
    base: '',
    plugins: [react(), viteTsconfigPaths()],
    server: {    
        // this ensures that the browser opens upon server start
        open: true,
        // this sets a default port to 3000, you can change this  
        port: 3000, 
    },
})
----

[#svelte-kit-config]
=== Svelte Kit Configuration
SvelteKit needs to be configured to create a single page application.
You will not be able to use any of its server-side only functionality.
See also https://kit.svelte.dev/docs/single-page-apps[SvelteKit documentation on Single-page apps].

Disable server side rendering at the root layout (`src/routes/+layout.js`):
[source,javascript]
----
export const ssr = false;
----

Install Svelte Static adapter:

[source,shell]
----
npm i -D @sveltejs/adapter-static
----

Configure `svelte.config.js` file with the following changes:

[source,javascript]
----
import adapter from '@sveltejs/adapter-static';

// In projects using Sveltekit v1
import { vitePreprocess } from '@sveltejs/kit/vite';

// In projects using SvelteKit v2
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte'

/** @type {import('@sveltejs/kit').Config} */
const config = {
    preprocess: vitePreprocess(),
    kit: {
        adapter: adapter({
            fallback: 'index.html'
        }),
        // Mark path non-relative, otherwise SvelteKit assumes it works in a sub-directory
        paths: {
            relative: false
        }
    }
};

export default config;
----

In `application.properties` add:
[source,properties]
----
quarkus.quinoa.build-dir=build
quarkus.quinoa.enable-spa-routing=true
%dev.quarkus.quinoa.dev-server.index-page=/
----

WARNING: Currently, for technical reasons, the Quinoa SPA routing configuration won't work with RESTEasy Classic. See xref:advanced-guides.adoc#spa-routing[SPA routing] for a workaround.

Dynamic routes in Svelte may also use invalid URL's accoring to the URL specific with `+` symbol in the URL.  See: https://github.com/quarkiverse/quarkus-quinoa/issues/591

To mitigate that you must disable Vert.X URL validation to work with dynamic routing using `-Dvertx.disableURIValidation=true` for example:

[source,bash]
----
mvn quarkus:dev -Dvertx.disableURIValidation=true
----